openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/gasstations/:
    get:
      operationId: listGasStations
      description: "\u0421\u043F\u0438\u0441\u043E\u043A \u0410\u0417\u0421"
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    lat:
                      type: number
                      nullable: true
                    lon:
                      type: number
                      nullable: true
                    number:
                      type: integer
                    region:
                      type: string
                      nullable: true
                      maxLength: 256
                    city:
                      type: string
                      nullable: true
                      maxLength: 256
                    street:
                      type: string
                      nullable: true
                      maxLength: 256
                    building:
                      type: string
                      nullable: true
                      maxLength: 256
                    zip_code:
                      type: string
                      nullable: true
                      maxLength: 6
                  required:
                  - number
          description: ''
  /api/fuels/:
    get:
      operationId: listFuels
      description: "\u0421\u043F\u0438\u0441\u043E\u043A \u0432\u0438\u0434\u043E\u0432\
        \ \u0442\u043E\u043F\u043B\u0438\u0432\u0430"
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    name:
                      type: string
                      maxLength: 256
                    image:
                      type: string
                      format: binary
                      nullable: true
                  required:
                  - name
          description: ''
  /api/fuel/{fuel_id}/:
    get:
      operationId: RetrieveFuel
      description: "\u041F\u043E\u043B\u0443\u0447\u0438\u0442\u044C \u0438\u043D\u0444\
        \u043E\u0440\u043C\u0430\u0446\u0438\u044E \u043F\u043E \u0432\u0438\u0434\
        \u0443 \u0442\u043E\u043F\u043B\u0438\u0432\u0430"
      parameters:
      - name: fuel_id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
    post:
      operationId: CreateFuel
      description: "\u0414\u043E\u0431\u0430\u0432\u0438\u0442\u044C \u0432\u0438\u0434\
        \ \u0442\u043E\u043F\u043B\u0438\u0432\u0430"
      parameters:
      - name: fuel_id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
  /api/services/:
    get:
      operationId: listServices
      description: "\u0421\u043F\u0438\u0441\u043E\u043A \u0432\u0438\u0434\u043E\u0432\
        \ \u0443\u0441\u043B\u0443\u0433"
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    name:
                      type: string
                      maxLength: 256
                    image:
                      type: string
                      format: binary
                      nullable: true
                  required:
                  - name
          description: ''
  /api/service/{service_id}/:
    get:
      operationId: RetrieveService
      description: "\u041F\u043E\u043B\u0443\u0447\u0438\u0442\u044C \u0438\u043D\u0444\
        \u043E\u0440\u043C\u0430\u0446\u0438\u044E \u043F\u043E \u0443\u0441\u043B\
        \u0443\u0433\u0435"
      parameters:
      - name: service_id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
    post:
      operationId: CreateService
      description: "\u0414\u043E\u0431\u0430\u0432\u0438\u0442\u044C \u0432\u0438\u0434\
        \ \u0442\u043E\u043F\u043B\u0438\u0432\u0430"
      parameters:
      - name: service_id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
  /api/gasstation/{station_id}/:
    get:
      operationId: RetrieveGasStation
      description: "\u041F\u043E\u043B\u043D\u0430\u044F \u0438\u043D\u0444\u043E\u0440\
        \u043C\u0430\u0446\u0438\u044F \u043F\u043E \u043E\u0434\u043D\u043E\u0439\
        \ \u0410\u0417\u0421 \u0441 \u0443\u0447\u0435\u0442\u043E\u043C \u043F\u0440\
        \u0438\u0432\u044F\u0437\u043A\u0438 \u0442\u043E\u043F\u043B\u0438\u0432\u0430\
        \ \u0438 \u0443\u0441\u043B\u0443\u0433"
      parameters:
      - name: station_id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
  /api/fuelsstation/{station_id}/:
    get:
      operationId: RetrieveFuelStation
      description: "\u041F\u043E\u043B\u0443\u0447\u0438\u0442\u044C \u0438\u043D\u0444\
        \u043E\u0440\u043C\u0430\u0446\u0438\u044E \u043F\u043E \u0446\u0435\u043D\
        \u0435 \u0442\u043E\u043F\u043B\u0438\u0432\u0430 \u0434\u043B\u044F \u0443\
        \u043A\u0430\u0437\u0430\u043D\u043D\u043E\u0439 \u0410\u0417\u0421"
      parameters:
      - name: station_id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
    post:
      operationId: CreateFuelStation
      description: "\u0414\u043E\u0431\u0430\u0432\u0438\u0442\u044C \u0446\u0435\u043D\
        \u0443 \u0442\u043E\u043F\u043B\u0438\u0432\u0443"
      parameters:
      - name: station_id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
  /api/servicesstation/{station_id}/:
    get:
      operationId: RetrieveServiceStation
      description: "\u041F\u043E\u043B\u0443\u0447\u0438\u0442\u044C \u0438\u043D\u0444\
        \u043E\u0440\u043C\u0430\u0446\u0438\u044E \u043F\u043E \u0446\u0435\u043D\
        \u0435 \u0443\u0441\u043B\u0443\u0433 \u0434\u043B\u044F \u0443\u043A\u0430\
        \u0437\u0430\u043D\u043D\u043E\u0439 \u0410\u0417\u0421"
      parameters:
      - name: station_id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
    post:
      operationId: CreateServiceStation
      description: "\u0414\u043E\u0431\u0430\u0432\u0438\u0442\u044C \u0446\u0435\u043D\
        \u0443 \u0443\u0441\u043B\u0443\u0433\u0435"
      parameters:
      - name: station_id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
