# Generated by Django 3.0.7 on 2020-06-04 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование топлива')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Топливо',
                'verbose_name_plural': 'Топливо',
            },
        ),
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='Стоимость топлива')),
                ('currency', models.CharField(max_length=50, verbose_name='Валюта')),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasstation.Fuel')),
            ],
        ),
        migrations.CreateModel(
            name='GasStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('lon', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('number', models.PositiveIntegerField(verbose_name='Номер АЗС')),
                ('address', models.CharField(max_length=256, verbose_name='Адрес АЗС')),
                ('fuel', models.ManyToManyField(through='gasstation.FuelStation', to='gasstation.Fuel')),
            ],
            options={
                'verbose_name': 'АЗС',
                'verbose_name_plural': 'АЗС',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Наименование услуги')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='ServiceStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='Стоимость услуги')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasstation.Service')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasstation.GasStation')),
            ],
        ),
        migrations.AddField(
            model_name='gasstation',
            name='service',
            field=models.ManyToManyField(through='gasstation.ServiceStation', to='gasstation.Service'),
        ),
        migrations.AddField(
            model_name='fuelstation',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gasstation.GasStation'),
        ),
    ]
