# Generated by Django 3.0.7 on 2020-06-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasstation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasstation',
            name='address',
        ),
        migrations.AddField(
            model_name='gasstation',
            name='building',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='gasstation',
            name='city',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Город РФ'),
        ),
        migrations.AddField(
            model_name='gasstation',
            name='region',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Регион РФ'),
        ),
        migrations.AddField(
            model_name='gasstation',
            name='street',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Улица'),
        ),
        migrations.AddField(
            model_name='gasstation',
            name='zip_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Индекс'),
        ),
    ]
