# Generated by Django 3.0.7 on 2020-06-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasstation', '0002_auto_20200604_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelstation',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость топлива'),
        ),
        migrations.AlterField(
            model_name='servicestation',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость услуги'),
        ),
    ]
