# Generated by Django 3.0.7 on 2020-06-04 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gasstation', '0003_auto_20200604_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelstation',
            name='fuel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuels', to='gasstation.Fuel'),
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuelstations', to='gasstation.GasStation'),
        ),
        migrations.AlterField(
            model_name='servicestation',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='gasstation.Service'),
        ),
        migrations.AlterField(
            model_name='servicestation',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicestations', to='gasstation.GasStation'),
        ),
    ]
