# Generated by Django 3.0.7 on 2020-06-04 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gasstation', '0004_auto_20200604_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuelstation',
            old_name='fuel',
            new_name='fuels',
        ),
        migrations.RenameField(
            model_name='fuelstation',
            old_name='station',
            new_name='stations',
        ),
        migrations.RenameField(
            model_name='servicestation',
            old_name='service',
            new_name='services',
        ),
        migrations.RenameField(
            model_name='servicestation',
            old_name='station',
            new_name='stations',
        ),
    ]
